services:
  api:
    build: .
    container_name: medistock_api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./firebase-key.json:/app/firebase-key.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: --reload

  postgres:
    image: postgres:16-alpine
    container_name: medistock_postgres
    environment:
      POSTGRES_USER: medistock
      POSTGRES_PASSWORD: medistock
      POSTGRES_DB: medistock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U medistock -d medistock" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: medistock_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
